REFACTOR: Upgrade Document Server to 7.3, adding JWT to the setup.

diff --git a/compose/production/documentserver/Dockerfile-staging b/compose/production/documentserver/Dockerfile-staging
--- a/compose/production/documentserver/Dockerfile-staging
+++ b/compose/production/documentserver/Dockerfile-staging
@@ -1,62 +1,64 @@
-FROM ubuntu:20.04
+ARG BASE_IMAGE=ubuntu:22.04
+
+FROM ${BASE_IMAGE} as documentserver
 LABEL maintainer Ascensio System SIA <support@onlyoffice.com>
 
-ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8 DEBIAN_FRONTEND=noninteractive PG_VERSION=12
+ARG PG_VERSION=14
+
+ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8 DEBIAN_FRONTEND=noninteractive PG_VERSION=${PG_VERSION}
 
 ARG ONLYOFFICE_VALUE=onlyoffice
 
 RUN echo "#!/bin/sh\nexit 0" > /usr/sbin/policy-rc.d && \
     apt-get -y update && \
-    apt-get -yq install wget apt-transport-https gnupg locales && \
-    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0x8320ca65cb2de8e5 && \
+    apt-get -yq install wget apt-transport-https gnupg locales lsb-release && \
     locale-gen en_US.UTF-8 && \
     echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections && \
     apt-get -yq install \
-        adduser \
-        apt-utils \
-        bomstrip \
-        certbot \
-        curl \
-        gconf-service \
-        htop \
-        libasound2 \
-        libboost-regex-dev \
-        libcairo2 \
-        libcurl3-gnutls \
-        libcurl4 \
-        libgtk-3-0 \
-        libnspr4 \
-        libnss3 \
-        libstdc++6 \
-        libxml2 \
-        libxss1 \
-        libxtst6 \
-        mysql-client \
-        vim \
-        net-tools \
-        netcat-openbsd \
-        nginx-extras \
-        postgresql \
-        postgresql-client \
-        pwgen \
-        rabbitmq-server \
-        redis-server \
-        software-properties-common \
-        sudo \
-        supervisor \
-        ttf-mscorefonts-installer \
-        xvfb \
-        zlib1g && \
+    adduser \
+    apt-utils \
+    bomstrip \
+    certbot \
+    curl \
+    gconf-service \
+    htop \
+    libasound2 \
+    libboost-regex-dev \
+    libcairo2 \
+    libcurl3-gnutls \
+    libcurl4 \
+    libgtk-3-0 \
+    libnspr4 \
+    libnss3 \
+    libstdc++6 \
+    libxml2 \
+    libxss1 \
+    libxtst6 \
+    mysql-client \
+    vim \
+    net-tools \
+    netcat-openbsd \
+    nginx-extras \
+    postgresql \
+    postgresql-client \
+    pwgen \
+    rabbitmq-server \
+    redis-server \
+    software-properties-common \
+    sudo \
+    supervisor \
+    ttf-mscorefonts-installer \
+    xvfb \
+    zlib1g && \
     if [  $(ls -l /usr/share/fonts/truetype/msttcorefonts | wc -l) -ne 61 ]; \
-        then echo 'msttcorefonts failed to download'; exit 1; fi  && \
+    then echo 'msttcorefonts failed to download'; exit 1; fi  && \
     echo "SERVER_ADDITIONAL_ERL_ARGS=\"+S 1:1\"" | tee -a /etc/rabbitmq/rabbitmq-env.conf && \
     sed -i "s/bind .*/bind 127.0.0.1/g" /etc/redis/redis.conf && \
     sed 's|\(application\/zip.*\)|\1\n    application\/wasm wasm;|' -i /etc/nginx/mime.types && \
     pg_conftool $PG_VERSION main set listen_addresses 'localhost' && \
     service postgresql restart && \
-    sudo -u postgres psql -c "CREATE DATABASE $ONLYOFFICE_VALUE;" && \
     sudo -u postgres psql -c "CREATE USER $ONLYOFFICE_VALUE WITH password '$ONLYOFFICE_VALUE';" && \
-    sudo -u postgres psql -c "GRANT ALL privileges ON DATABASE $ONLYOFFICE_VALUE TO $ONLYOFFICE_VALUE;" && \
+    sudo -u postgres psql -c "CREATE DATABASE $ONLYOFFICE_VALUE OWNER $ONLYOFFICE_VALUE;" && \
     service postgresql stop && \
     service redis-server stop && \
     service rabbitmq-server stop && \
@@ -70,22 +72,27 @@ COPY ./compose/production/documentserver/overides.css /opt/overides.css
 COPY ./compose/production/nginx/dhparams.pem /var/www/onlyoffice/Data/certs/dhparam.pem
 COPY ./compose/production/documentserver/run-document-server.sh /app/ds/run-document-server.sh
 
-EXPOSE 80 443
-
-ARG REPO_URL="deb http://download.onlyoffice.com/repo/debian squeeze main"
 ARG COMPANY_NAME=onlyoffice
 ARG PRODUCT_NAME=documentserver
+ARG PRODUCT_EDITION=
+ARG PACKAGE_VERSION=
+ARG TARGETARCH
+ARG PACKAGE_BASEURL="http://download.onlyoffice.com/install/documentserver/linux"
 
 ENV COMPANY_NAME=$COMPANY_NAME \
-    PRODUCT_NAME=$PRODUCT_NAME
+    PRODUCT_NAME=$PRODUCT_NAME \
+    PRODUCT_EDITION=$PRODUCT_EDITION \
+    DS_DOCKER_INSTALLATION=true
 
-RUN echo "$REPO_URL" | tee /etc/apt/sources.list.d/ds.list && \
+RUN PACKAGE_FILE="${COMPANY_NAME}-${PRODUCT_NAME}${PRODUCT_EDITION}${PACKAGE_VERSION:+_$PACKAGE_VERSION}_${TARGETARCH:-$(dpkg --print-architecture)}.deb" && \
+    wget -q -P /tmp "$PACKAGE_BASEURL/$PACKAGE_FILE" && \
     apt-get -y update && \
     service postgresql start && \
-    apt-get -yq install $COMPANY_NAME-$PRODUCT_NAME && \
+    apt-get -yq install /tmp/$PACKAGE_FILE && \
     service postgresql stop && \
     service supervisor stop && \
     chmod 755 /app/ds/*.sh && \
+    rm -f /tmp/$PACKAGE_FILE && \
     rm -rf /var/log/$COMPANY_NAME && \
     rm -rf /var/lib/apt/lists/*
 
